### ISSUE TITLE
Zsh prompt configuration does't seem to match project screenshots

### ISSUE THREAD

**Issue by hamidb** [joshukraine/dotfiles#55]
Hi, 
I just tried to use zshrc configuration in which prompt file was sourced.
However, I am confused since the result of my zsh is not the same as screenshots in the [README.md](https://github.com/joshukraine/dotfiles/blob/master/README.md) page.

Here is how my zsh looks:

![](https://images2.imgbox.com/51/b6/ffa7hJjC_o.png)

And the screenshot:
![](https://camo.githubusercontent.com/8c3f55646651273908ff82219b3374f6a9b081c5cffe164ba45dce26bc44c8e5/68747470733a2f2f7265732e636c6f7564696e6172792e636f6d2f646e6b7673696a7a752f696d6167652f75706c6f61642f76313538373832323635372f73637265656e73686f74732f6f6e652d68616c662d6461726b2d73616d706c655f726e356664732e706e67)

Am I missing something?

**Comment by joshukraine** [comment]
@hamidb Yes, the difference is because I include configs for two shells: fish and zsh. I used to use zsh as my main shell, and the prompt you're seeing was the one I used at that time. However, my current daily driver is fish, and with that config I use the [Starship](https://starship.rs/) prompt.

Starship also supports zsh, but since I don't use zsh anymore I haven't taken the time to update it. If you're interested in doing that, I'd be happy to accept a PR! 🙂

**Comment by hamidb** [comment]
Thanks @joshukraine 
It makes sense. I also managed to replicate the screenshots using spaceship prompt. 
As it's purely taken from [spaceship-prompt](https://github.com/denysdovhan/spaceship-prompt), there's no point in creating a PR out of it.
Btw, thanks for sharing your cool and organised dotfiles. I almost took it without change.

**Comment by joshukraine** [comment]
@hamidb You're quite welcome. Thanks for the kind words. 🙂  Have a great weekend!
